name: flutter_localisation
description: A command-line tool for generating localization files for different flavors.
version: 2.1.0
repository: https://github.com/tajaouart/flutter_localisation

environment:
  sdk: ^3.4.1

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  http: ^1.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  mockito: ^5.4.6
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  test: ^1.16.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

executables:
  flutter_localisation: flutter_localisation
  generate: generate
flutter:
  generate: true